# Copyright (c) 2025-2026 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause

import os

import platformdirs

__version__ = "1.4.0"

# Configs bundled with the package. Only the synthesized FTDI Alpaca-Lite
# default (TAC_FTDI_13.tcnf) ships here; the full config set (every .tcnf plus
# devicelist.json) is fetched with the "installconfigs" subcommand.
PACKAGE_TAC_CONFIG_PATH = os.path.join(os.path.dirname(__file__), "tac_configs")

# Where "installconfigs" writes the full config set by default.
INSTALLED_TAC_CONFIG_PATH = platformdirs.user_data_dir("pytactl")

# Default config repository fetched by "installconfigs".
DEFAULT_CONFIG_REPOSITORY = (
    "https://github.com/qualcomm/qcom-test-automation-controller/"
)

# Filename of the default FTDI Alpaca-Lite config used as a fallback. The upstream
# repository has no .tcnf for it (it is generated by FTDIPlatformConfiguration.cpp),
# so "installconfigs" copies the bundled TAC_FTDI_13.tcnf under this name.
DEFAULT_CONFIG_FILENAME = "default.tcnf"


def default_tac_config_path():
    """Resolve the default TAC config directory.

    Prefer the installed config set (populated by "installconfigs") when it
    exists and is non-empty; otherwise fall back to the configs bundled with
    the package.
    """
    installed = INSTALLED_TAC_CONFIG_PATH
    if os.path.isdir(installed) and os.listdir(installed):
        return installed
    return PACKAGE_TAC_CONFIG_PATH


# Backwards-compatible module-level default; resolved at import time.
DEFAULT_TAC_CONFIG_PATH = default_tac_config_path()
