# Copyright (c) 2026 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause

import logging
import os
import subprocess
import sys

from .debugboard import Board

logger = logging.getLogger()

# Where "installudevrules" writes the rules by default.
DEFAULT_RULES_PATH = "/etc/udev/rules.d/99-pytac.rules"

# pyusb has to open the USB device node to read its serial-number string
# descriptor when resolving --serial, which the default root-only permissions
# forbid ("list" works without this because pyserial reads the serial number
# from sysfs). MODE/GROUP covers headless plugdev members; TAG+="uaccess"
# grants the locally logged-in desktop user access via ACL.
_USB_RULE = (
    'SUBSYSTEM=="usb", ATTR{{idVendor}}=="{vid:04x}", '
    'ATTR{{idProduct}}=="{pid:04x}", MODE="0660", GROUP="plugdev", '
    'TAG+="uaccess"'
)

# Bughopper V2 is driven over HID, so its hidraw node needs a rule as well.
# hidraw devices carry no idVendor/idProduct of their own, hence ATTRS
# (parent attributes) instead of ATTR.
_HIDRAW_RULE = (
    'SUBSYSTEM=="hidraw", ATTRS{{idVendor}}=="{vid:04x}", '
    'ATTRS{{idProduct}}=="{pid:04x}", MODE="0660", GROUP="plugdev", '
    'TAG+="uaccess"'
)


def generate_rules():
    """Return the udev rules file content covering every known debug board."""
    lines = [
        "# udev rules for Qualcomm debug boards (TAC/Alpaca).",
        "# Generated by 'pytac installudevrules'; do not edit by hand.",
        "",
    ]
    for (vid, pid), board_type in sorted(Board.known_boards().items()):
        lines.append(f"# {board_type}")
        lines.append(_USB_RULE.format(vid=vid, pid=pid))
    lines.append("# Bughopper V2 HID interface")
    lines.append(
        _HIDRAW_RULE.format(
            vid=Board.ID_VENDOR_BUGHOPPER_V2, pid=Board.ID_PRODUCT_BUGHOPPER_V2
        )
    )
    lines.append("")
    return "\n".join(lines)


def _run(cmd, **kwargs):
    logger.debug("Running: %s", " ".join(cmd))
    try:
        subprocess.run(cmd, check=True, **kwargs)
    except FileNotFoundError:
        logger.error("Command not found: %s", cmd[0])
        sys.exit(1)
    except subprocess.CalledProcessError as e:
        logger.error(
            "Command failed with exit code %d: %s", e.returncode, " ".join(cmd)
        )
        sys.exit(1)


def install_udev_rules(rules_path=None, dry_run=False):
    """Install udev rules for all known debug boards and reload udev.

    Writes ``rules_path`` directly when running as root; otherwise only the
    privileged steps (writing the file, reloading udev) are run through
    ``sudo``, so this works for a pipx-installed pytac that is not on root's
    PATH. With ``dry_run`` the rules are printed to stdout and nothing is
    touched.
    """
    rules_path = rules_path or DEFAULT_RULES_PATH
    rules = generate_rules()

    if dry_run:
        print(rules, end="")
        return

    if sys.platform != "linux":
        logger.error("udev is Linux-only; nothing to install on %s", sys.platform)
        sys.exit(1)

    if os.geteuid() == 0:
        with open(rules_path, "w") as f:
            f.write(rules)
        _run(["udevadm", "control", "--reload-rules"])
        _run(["udevadm", "trigger"])
    else:
        logger.info("Not running as root; installing %s via sudo", rules_path)
        _run(
            ["sudo", "tee", rules_path],
            input=rules.encode(),
            stdout=subprocess.DEVNULL,
        )
        _run(["sudo", "udevadm", "control", "--reload-rules"])
        _run(["sudo", "udevadm", "trigger"])

    print(f"Installed udev rules to {rules_path}")
    print(
        "Boards are now accessible to locally logged-in users and to members\n"
        "of the 'plugdev' group. To add your user to the group, run:\n"
        "    sudo usermod -aG plugdev $USER\n"
        "and log out and back in. Replug the board if it is currently connected\n"
        "and permissions do not apply."
    )
